package com.dayday.up.test.anotation.autoGenerated.unparameterized.TestAnotationController;

import com.dayday.up.test.anotation.TestAnotationController;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Auto-Generated: Do not modify it
 */
@SuppressWarnings("all")
@Slf4j
public class TestAnotationControllerTest extends AbstractTest implements TestAnotationControllerTestInterface {
    @Autowired
    private TestAnotationController testAnotationController;

    @Test
    public void hello(){
    }
    @Override
    public void afterTestShowData() throws Exception {
        
    }

    @Override
    public void afterTestCleanData() throws Exception {

    }
}

