package com.dayday.up.test.anotation.autoGenerated.unparameterized.TestAnotationController;

/**
 * Created with IntelliJ IDEA.
 * User: admin
 * Date: 2020-06-02
 * Time: 21:57
 */
public interface TestAnotationControllerTestInterface {
    void afterTestShowData() throws Exception;

    void afterTestCleanData() throws Exception;
}
